### ISSUE TITLE
the table in subtask and related issue

### ISSUE THREAD

**Issue by ashrafalzyoud** [alphanodes/redmine_issue_view_columns#2]
the table need resize

**Comment by ashrafalzyoud** [comment]
and can u let compitable with this plugin
https://github.com/sk-ys/redmine_subtask_list_accordion
becase all column hidden

**Comment by alexandermeindl** [comment]
> the table need resize

What table do you mean? This fork of the plugin uses autoscroll for vertical scrolling, resize is not supported because of this reason.

**Comment by ashrafalzyoud** [comment]
![555555](https://user-images.githubusercontent.com/50211455/178894501-8bb868ff-8122-4587-83c0-8c9e0964c26b.png)
look to subject column
and serial#

**Comment by alexandermeindl** [comment]
Your subject column looks quite large. Do you use any custom style for that? Or do you use another plugin, which change the width of subject column? I think, if this column width is smaller, it should look ok. redmine_issue_view_columns do not set a width for subject column.

Try it without https://github.com/sk-ys/redmine_subtask_list_accordion

**Comment by ashrafalzyoud** [comment]
im now not using https://github.com/sk-ys/redmine_subtask_list_accordion now becuase not compitable
but also subject column its still large

**Comment by alexandermeindl** [comment]
Check your theme or other plugins. As I said, this plugin does not change width of subject column. Make sure you use latest version of main branch. I had trouble with the width of subject in past, too.
Find out where the width of the subject is coming from.

I hope this infos help you to fix your problem. If not, provide a propose for a change with  a PR.

**Comment by ashrafalzyoud** [comment]
when im using this plugin
https://github.com/san199332/redmine_issue_view_columns
its work for me and subject column size its ok
check plz about the table width

**Comment by ashrafalzyoud** [comment]
apllicaition .css line  569
if the width auto ok to your plugin
```
#issue_tree .issue > td.subject, #relations .issue > td.subject {
  width: 100%; /* let subject have one full width column */
  word-break: break-word; /* break word if subject is too long */
  padding-right: 25px; /* this is the spaces that .buttons uses next to subject */
}
```

**Comment by alexandermeindl** [comment]
Hi @ashrafalzyoud,

I can confirm, that with the latest Redmine update with https://www.redmine.org/issues/36453 this is problem. I'll try to find a solution.

**Comment by ClaudiaMeindl** [comment]
Hi @ashrafalzyoud,

there has been some changes to the CSS file, pleas try it out, if it also works for you.
Thank you.

**Comment by ashrafalzyoud** [comment]
@ClaudiaMeindl  the same problem subject column resize

**Comment by ClaudiaMeindl** [comment]
Hi @ashrafalzyoud,

what the CSS customization does is:
- it sets a minimum width for the "Issue subject" column
- tested in various browsers

It should work, please clear the browser cache.
Thank you.
